apiVersion: v2
name: gke-platform
description: Enterprise GKE platform chart — NGINX ingress, namespaces, RBAC, resource quotas
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords: [gke, kubernetes, platform, ingress, rbac]
maintainers:
  - name: Paul Nyoike
    url: https://github.com/NyoikePaul
icon: https://helm.sh/img/helm.svg
